name: CI

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                # Clone all history so timestamps are accurate
                fetch-depth: 0

          - name: Set up dependencies
            run: sudo apt install -y brotli

          - name: Build
            run: bash -e build.sh

          - name: Compress
            run: brotli -Z build/domains.txt build/hosts.txt

          - name: Publish
            run: |
                mkdir -p ~/.ssh/
                echo "|1|pqAYcGlAgWemTBdNr+eYL/BrYOc=|yC8+igyEU5ldFvLoYKujPTdEbKg= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJSgweEQn216+sUrv4A0HwrnvJi03tu/LPeJ176yB29a" >~/.ssh/known_hosts
                chmod 600 ~/.ssh/known_hosts
                echo "${{ secrets.SSH_KEY }}" >~/.ssh/id_ed25519
                chmod 400 >~/.ssh/id_ed25519
                sftp orcapetlmg@ftp.cluster021.hosting.ovh.net <<'EOF'
                lcd build
                cd www/notonmyshift
                put domains.txt
                put hosts.txt
                EOF
