name: CI

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                # Clone all history so timestamps are accurate
                fetch-depth: 0

          - name: Set up dependencies
            run: sudo apt install -y brotli

          - name: Build
            run: bash -e build.sh

          - name: Compress
            run: brotli -Z build/domains.txt build/hosts.txt

          - name: Publish
            uses: socram8888/ftp-hash-sync@v1
            with:
                host: ftp.cluster021.hosting.ovh.net
                username: orcapetlmg
                password: ${{ secrets.FTP_PASSWORD }}
                source: build
                destination: www/notonmyshift
                hashfile: domains.sha256
