name: CI

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
          - name: Checkout source
            uses: actions/checkout@v2
            with:
                # Clone just last ten which should be enough to have the hosts timestamp
                fetch-depth: 10

          - name: Checkout orca.pet
            uses: actions/checkout@v2
            with:
                repository: socram8888/orca.pet
                ref: gh-pages
                path: orca.pet

          - name: Build
            run: |
                bash -e build.sh
                cp build/domains.txt orca.pet/notonmyshift/domains.txt
                cp build/hosts.txt orca.pet/notonmyshift/hosts.txt

          - name: Publish
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
                commit_message: 'Automatic build (Not on my shift)'
                repository: orca.pet
                branch: gh-pages
