name: CI

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
          - name: Checkout source
            uses: actions/checkout@v2
            with:
                # Clone just last ten which should be enough to have the hosts timestamp
                fetch-depth: 10

          - name: Checkout orca.pet
            uses: actions/checkout@v2
            with:
                repository: socram8888/orca.pet
                ref: gh-pages
                path: orca.pet
                token: ${{ secrets.COMMIT_TOKEN }}

          - name: Setup Python
            uses: actions/setup-python@v1
            with:
                python-version: 3.7

          - name: Setup Pip cache
            uses: actions/cache@v1
            with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-

          - name: Build
            run: |
                pip install -r requirements.txt
                python build.py filters.yml --abp orca.pet/notonmyshift/abp.txt --domains orca.pet/notonmyshift/domains.txt --hosts orca.pet/notonmyshift/hosts.txt

          - name: Publish
            uses: stefanzweifel/git-auto-commit-action@v4.3.0
            with:
                commit_message: 'Automatic build (Not on my shift)'
                repository: orca.pet
                branch: gh-pages
